### ISSUE TITLE
Media References do not work

### ISSUE THREAD

**Issue by amtee** [jonnitto/Jonnitto.Plyr#2]
When I add a video File at the inspector I get a success message. Right after the page reload when "apply" was clicked this huge Error 500.
After that there is no file referenced in the inspector anymore. It does work with image. 
Even more remarkable is, that the video is rendered in frontend.

Tested on 2 different servers and different setups. Both Neos 3.1. One of them was fresh out of the box.

```
Exception while property mapping for target type "array", at property path "0": It is not allowed to map property "__initializer__".It is not allowed to map property "__initializer__".
You need to use $propertyMappingConfiguration->allowProperties('__initializer__') to enable mapping of this property.Exception Code1297759968Exception TypeNeos\Flow\Property\ExceptionLog Reference20170608161011564e18Thrown in FileData/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Property_PropertyMapper.phpLine129Original FilePackages/Framework/Neos.Flow/Classes/Property/PropertyMapper.php
Nested ExceptionYou need to use $propertyMappingConfiguration->allowProperties('__initializer__') to enable mapping of this property.Exception Code1335969887Exception TypeNeos\Flow\Property\Exception\InvalidPropertyMappingConfigurationExceptionLog Reference20170608161011b3769aThrown in FileData/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Property_PropertyMapper.phpLine186Original FilePackages/Framework/Neos.Flow/Classes/Property/PropertyMapper.php
```
![bildschirmfoto 2017-06-08 um 16 08 57](https://user-images.githubusercontent.com/17073000/26934466-bfb90236-4c69-11e7-9617-c4b01ccfcc24.png)

**Comment by amtee** [comment]
Actually this seems to be a Neos-based problem! When I insert an Asset List NodeType I run into the same issues.

Done here!

**Comment by jonnitto** [comment]
Yes. I had the same issue on a Neos Project. There's already a bugfix: https://github.com/neos/neos-development-collection/pull/1569
