### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by tbrodard** [jonnitto/Jonnitto.Plyr#23]
**Is your feature request related to a problem? Please describe.**
Redactor don't understand why Youtube videos can be played in a lightbox (through https://github.com/jonnitto/Jonnitto.PrettyEmbedYoutube) and not for .mp4 videos

**Describe the solution you'd like**
The same option "Open Video in a Lightbox", as for PrettyEmbedYoutube

**Describe alternatives you've considered**
-

**Additional context**
... ready to sponsor this feature, please DM on Slack !

**Comment by jonnitto** [comment]
Thank you @tbrodard for your sponsoring support for https://github.com/jonnitto/Jonnitto.PrettyEmbedVideo
