### ISSUE TITLE
Fusion <-> TypoScript in v0.2.6

### ISSUE THREAD

**Issue by dsjiern** [jonnitto/Jonnitto.Plyr#3]
There is an error in the Tag.ts2:
`@exceptionHandler = 'TYPO3\\Neos\\**Fusion**\\ExceptionHandlers\\NodeWrappingHandler'`
it have to be:
`@exceptionHandler = 'TYPO3\\Neos\\**TypoScript**\\ExceptionHandlers\\NodeWrappingHandler'`

**Comment by jonnitto** [comment]
Solved with release [0.2.7](https://github.com/jonnitto/Jonnitto.Plyr/releases/tag/0.2.7)
